### ISSUE TITLE
Change ModernExtension properties at runtime not working when the icon is in RightWindowCommands/ToggleButton

### ISSUE THREAD

**Issue by UlyssesWu** [MahApps/MahApps.Metro.IconPacks#176] opened 2020-02-16 18:11 UTC
**Describe the bug**
Changing `ModernExtension.Spin` or `ModernExtension.Kind` at runtime is not taking affect when the icon is located in `MetroWindow.RightWindowCommands`.

**To Reproduce**
1.  In MainWindow.xaml:

```
    <controls:MetroWindow.RightWindowCommands>
        <controls:WindowCommands>
            <ToggleButton x:Name="ToggleNc" Focusable="False">
                <iconPacks:Modern x:Name="IconNc" Kind="HardwareHeadphones" Spin='True' />
            </ToggleButton>
        </controls:WindowCommands>
    </controls:MetroWindow.RightWindowCommands>
```

2. Set `IconNc.Spin = false` at `MainWindow.xaml.cs`
3. The icon is still spinning.
4. Set `IconNc.Kind` to other values won't work either.

**Expected behavior**
The icon stops spinning after `IconNc.Spin = false`.

**ScreenShot**

**Desktop Environment (please complete the following information):**
 - IconPacks Version: v3.2.0
 - Visual Studio: 2019
 - .NET Framework: 4.8
- MahApps.Metro: v1.6.5

**Comment by UlyssesWu** [comment] 2020-02-17 14:25
This seems only happens for a `ToggleButton` in `WindowCommands`. If I use a `Button` instead of a `ToggleButton`, it works as usual.

**Comment by punker76** [comment] 2020-02-25 20:39
@UlyssesWu The problem is that you are using the MarkupExtension and not the PackIcon class itself. The provided properties of the MarkupExtension doesn't update the properties on the provided PackIcon class. So if you use the PackIcon class your problem will be fixed.

```xaml
<mah:MetroWindow.RightWindowCommands>
    <mah:WindowCommands>
        <Button x:Name="ToggleNc" Focusable="False">
            <iconPacks:PackIconModern x:Name="IconNc" Kind="HardwareHeadphones" Spin='True' />
        </Button>
    </mah:WindowCommands>
</mah:MetroWindow.RightWindowCommands>
```

**Closed by punker76** 2020-02-25 20:39 UTC
Labels: Bug
