### ISSUE TITLE
Use Iconpack as Image

### ISSUE THREAD

**Issue by SurtursRevenge** [MahApps/MahApps.Metro.IconPacks#39] opened 2017-03-17 13:19 UTC
Hi everyone

I want to use some Icons if this Pack as Images, so everthink looks the same.
But i don't know how to access the Images ....

`xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks" 

this works  : <Button Content="{iconPacks:PackIconMaterial Settings}"

here i wan't to use the Image ... This doesn't work :
<myWPF:ImageButton Image="{iconPacks:PackIconMaterial Settings}" `

So how can i get or convert the iconPacks to an Image Source ?

**Comment by punker76** [comment] 2017-03-17 13:20
@SurtursRevenge Why do you want to convert it to an image?

**Comment by SurtursRevenge** [comment] 2017-03-17 13:25
@punker76 
For buttons with text and a picture we use custom WPF ( -> myWPF:ImageButton)
This requires an Image="file.png" or static resource etc as an input.
But i want to use the Icons of this pack as Image. So now i need to get them as image source or something like that, so the can be used.

Or am i getting something totally wrong ?

**Comment by themiwi** [comment] 2017-03-17 19:03
Another application would be using the icons for `RibbonButton` which requires a `LargeImageSource` and a `SmallImageSource`.

**Comment by Insire** [comment] 2017-03-17 19:55
You can convert the path from the PackIcon to a geometry object, then manipulate it as you please. Maybe fill it with a color? Once you are done with setting it up, you can convert it to bitmap or png and write it to file. You can look at [this](https://github.com/Insire/Maple/blob/master/InsireBot/InsireBot/Controls/IoCWindow.cs#L37) for inspiration. Only the file part is missing, but you should be able to figure that out.

**Comment by SurtursRevenge** [comment] 2017-03-20 11:07
@Insire 
But can i do this in XAML ?

**Comment by Insire** [comment] 2017-03-20 12:30
Yes, why wouldnt you?

**Comment by SurtursRevenge** [comment] 2017-03-20 13:02
@Insire 
Than i am to stupid :/

When trying this Image="{iconPacks:PackIconMaterial Settings}"

I get a XAML Parser Exception with inner exception 
{"The Object of typ \"MahApps.Metro.IconPacks.PackIconMaterial\" could not be converted to typ \"System.Windows.Media.ImageSource\" "}

**Comment by themiwi** [comment] 2017-03-20 14:52
I solved it for my use-case with a new markup extension:
```csharp
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Media;

namespace MahApps.Metro.IconPacks
{
	public abstract class PackIconImageSourceExtension<TKind> : MarkupExtension
	{
		[ConstructorArgument("kind")]
		public TKind Kind { get; set; }


		public Pen Pen { get; set; } = new Pen(Brushes.Black, 1);


		public Brush Brush { get; set; } = Brushes.Black;


		public abstract Transform Transform { get; set; }


		public IValueConverter Converter { get; set; }


		public object ConverterParameter { get; set; }


		protected PackIconImageSourceExtension()
		{
		}


		protected PackIconImageSourceExtension(TKind kind)
		{
			Kind = kind;
		}


		private ImageSource GetImageSource(TKind kind, Pen pen, Brush brush, Transform transform, IValueConverter converter, object parameter)
		{
			if (_data == null)
			{
				_data = new Lazy<IDictionary<TKind, string>>(GetDataFactory());
			}

			var geom = new GeometryDrawing
			{
				Geometry = Geometry.Parse(_data.Value[kind]),
			};
			if (pen != null)
			{
				geom.Pen = pen;
			}
			if (brush != null)
			{
				geom.Brush = brush;
			}
			var grp = new DrawingGroup
			{
				Transform = transform,
				Children = { geom },
			};
			ImageSource result = new DrawingImage
			{
				Drawing = grp,
			};
			if (converter != null)
			{
				result = (ImageSource)converter.Convert(result, typeof(ImageSource), parameter, CultureInfo.CurrentCulture);
			}
			return result;
		}


		public override object ProvideValue(IServiceProvider serviceProvider)
		{
			return GetImageSource(Kind, Pen, Brush, Transform, Converter, ConverterParameter);
		}


		protected abstract Func<IDictionary<TKind, string>> GetDataFactory();


		private static Lazy<IDictionary<TKind, string>> _data;
	}


	[MarkupExtensionReturnType(typeof(ImageSource))]
	public class PackIconEntypoImageSourceExtension
		: PackIconImageSourceExtension<PackIconEntypoKind>
	{
		public PackIconEntypoImageSourceExtension()
		{ }


		public PackIconEntypoImageSourceExtension(PackIconEntypoKind kind) : base(kind)
		{ }


		public override Transform Transform { get; set; } = new ScaleTransform(1, -1);


		protected override Func<IDictionary<PackIconEntypoKind, string>> GetDataFactory()
		{
			return PackIconEntypoDataFactory.Create;
		}
	}


	[MarkupExtensionReturnType(typeof(ImageSource))]
	public class PackIconFontAwesomeImageSourceExtension
		: PackIconImageSourceExtension<PackIconFontAwesomeKind>
	{
		public PackIconFontAwesomeImageSourceExtension()
		{ }


		public PackIconFontAwesomeImageSourceExtension(PackIconFontAwesomeKind kind) : base(kind)
		{ }


		public override Transform Transform { get; set; } = new ScaleTransform(1, -1);


		protected override Func<IDictionary<PackIconFontAwesomeKind, string>> GetDataFactory()
		{
			return PackIconFontAwesomeDataFactory.Create;
		}
	}


	[MarkupExtensionReturnType(typeof(ImageSource))]
	public class PackIconMaterialImageSourceExtension
		: PackIconImageSourceExtension<PackIconMaterialKind>
	{
		public PackIconMaterialImageSourceExtension()
		{ }


		public PackIconMaterialImageSourceExtension(PackIconMaterialKind kind) : base(kind)
		{ }


		public override Transform Transform { get; set; } = null;


		protected override Func<IDictionary<PackIconMaterialKind, string>> GetDataFactory()
		{
			return PackIconMaterialDataFactory.Create;
		}
	}


	[MarkupExtensionReturnType(typeof(ImageSource))]
	public class PackIconModernImageSourceExtension
		: PackIconImageSourceExtension<PackIconModernKind>
	{
		public PackIconModernImageSourceExtension()
		{ }


		public PackIconModernImageSourceExtension(PackIconModernKind kind) : base(kind)
		{ }


		public override Transform Transform { get; set; } = null;


		protected override Func<IDictionary<PackIconModernKind, string>> GetDataFactory()
		{
			return PackIconModernDataFactory.Create;
		}
	}


	[MarkupExtensionReturnType(typeof(ImageSource))]
	public class PackIconOcticonsImageSourceExtension
		: PackIconImageSourceExtension<PackIconOcticonsKind>
	{
		public PackIconOcticonsImageSourceExtension()
		{ }


		public PackIconOcticonsImageSourceExtension(PackIconOcticonsKind kind) : base(kind)
		{ }


		public override Transform Transform { get; set; } = null;


		protected override Func<IDictionary<PackIconOcticonsKind, string>> GetDataFactory()
		{
			return PackIconOcticonsDataFactory.Create;
		}
	}
}
```

Will submit it as a pull-request once I get the time to clean up a bit.

**Comment by Insire** [comment] 2017-03-20 16:15
@themiwi got my idea. there are several ways to accomplish what you wanted @SurtursRevenge Using a markup extension, is one way, you could also use a custom converter. Also putting that logic into your viewmodel would be possible too, although i wouldnt recommend doing that.

**Comment by Phyxion** [comment] 2017-04-07 08:09
I use an IValueConverter for this, which is slightly more useful than a markup extension as you can also use bindings. 

For example:
`ImageSource="{Binding Source={x:Static iconPacks:PackIconEntypoKind.AddToList}, Converter={common:PackIconEntypoImageSourceConverter}, ConverterParameter={StaticResource TextBrush}}"
`

or like this:

`ImageSource="{Binding Path=AddToListIcon, Converter={common:PackIconEntypoImageSourceConverter}, ConverterParameter={StaticResource TextBrush}}"`

There are absolutely valid reasons for having the icons as an image, as mentioned here already. I'd like to see this added to the IconPacks.

Here's the full code to the converters I'm using. Feel free to use it as you want.
https://gist.github.com/Phyxion/ed9309d2d727f49faba44d1d2fc966ce

**Comment by punker76** [comment] 2017-04-07 08:56
@Phyxion 👍  I'll also add PackIconImageXYZ classes derived from Image which will have the same power as the icons.

**Comment by Phyxion** [comment] 2017-04-07 09:12
Updated the gist file, I didn't really check the other icons as I mainly use Modern, but the pen thickness wasn't correct for most, making them drawn way too fat. This is now corrected :)

**Comment by Phyxion** [comment] 2017-04-07 11:04
It seems that if you use 0.25 as a Pen thickness for all converters it's the best result for all sizes. This also has the added advantage that - apart from the Material Light - they are all drawn at roughly the same thickness, so it's easier to use icons from different packs together. 

Perhaps it'd be a nice addition to add a property to the converter to specifiy the Pen's thickness. Although you'd need to declare the converter first, it shouldn't be such as issue as you can do something like yourself in App.xaml
`<converters:PackIconImageSourceConverter x:Key="ThickPackImageSourceConverter" PenThickness="1.0"/>`
and simply refer to ThickPackImageSourceConverter instead of the PackIconImageSourceConverter itself.

**Comment by punker76** [comment] 2018-10-22 21:47
Duplicate of #57

**Closed by punker76** 2018-10-22 21:47 UTC
Labels: Feature

**Comment by Phyxion** [comment] 2018-10-23 06:51
@punker76 Should the other issue be closed? This one is older and has a lot more information.
